### ISSUE TITLE
403 permission denied

### ISSUE THREAD

**Issue by JAStark** [radiodraws/relacion-territorio#1]
Hi Carolina! The description sounds so great, but the link in the readme to see the map returns a 403 - permission to access the server is denied 😢 

> Forbidden
>You don't have permission to access /test/relacion-territorio/ on this server.
>Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle >the request.

I hope it's not too tricky to fix 💃

**Comment by carolina-vallejo** [comment]
Hi JAStark, is strange I just tested in different devices and I can load the page, you could try again in a while, perhaps was for some temporary server error.

**Comment by JAStark** [comment]
ahh weird! It was because of my VPN. Sorry about that! 🦄
